# Start from a core stack version
FROM jupyter/tensorflow-notebook
# Install in the default python3 environment
#RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
#RUN jupyter labextension install ipysheet
RUN conda install -c conda-forge ipysheet qtconsole
RUN conda install -c anaconda pyqt

RUN jupyter labextension install @jupyterlab/toc
#RUN jupyter labextension install jupyterlab-clipboard
